version: "3.10"

services:
  db:
    image: postgres:16.0
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=events
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGUSER=postgres
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: -p 5433

  app:
    build: ./src
    container_name: fastapi
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001


networks:
  default:
      name: events_network